// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBimJj9tk1zC1MCGa-wUvq9fdW4NFcxru8',
    appId: '1:972604251112:web:3dba28cccf76d3e073a25d',
    messagingSenderId: '972604251112',
    projectId: 'cofify-a8db2',
    authDomain: 'cofify-a8db2.firebaseapp.com',
    storageBucket: 'cofify-a8db2.appspot.com',
    measurementId: 'G-QHLBBMD2SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAre0FeWygP4L1FmO5xGxEEUuN2sWJqf7c',
    appId: '1:972604251112:android:7a5215ded04b873473a25d',
    messagingSenderId: '972604251112',
    projectId: 'cofify-a8db2',
    storageBucket: 'cofify-a8db2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZXiucAixn8Ah1JJp64rkkV3cECQvQGZ4',
    appId: '1:972604251112:ios:f8bca12a23a431ab73a25d',
    messagingSenderId: '972604251112',
    projectId: 'cofify-a8db2',
    storageBucket: 'cofify-a8db2.appspot.com',
    androidClientId: '972604251112-l99beecorkvm8eoj81rkjvq06d3p16n3.apps.googleusercontent.com',
    iosClientId: '972604251112-32be2sehbdk23qteu7snkialhdjr6su0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cofify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZXiucAixn8Ah1JJp64rkkV3cECQvQGZ4',
    appId: '1:972604251112:ios:561b61d153c9136373a25d',
    messagingSenderId: '972604251112',
    projectId: 'cofify-a8db2',
    storageBucket: 'cofify-a8db2.appspot.com',
    androidClientId: '972604251112-l99beecorkvm8eoj81rkjvq06d3p16n3.apps.googleusercontent.com',
    iosClientId: '972604251112-cqi30t0eeg5meq8bbspj76et154bgu07.apps.googleusercontent.com',
    iosBundleId: 'com.example.cofify.RunnerTests',
  );
}
